"""add resume_profile to ingested_files

Revision ID: 13332a9b932b
Revises: 69dc4a4fd972
Create Date: 2026-01-14 18:47:36.286028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '13332a9b932b'
down_revision: Union[str, Sequence[str], None] = '69dc4a4fd972'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingested_files', sa.Column('resume_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingested_files', 'resume_profile')
    # ### end Alembic commands ###
